### ISSUE TITLE
How to install and use

### ISSUE THREAD

**Issue by ateproni** [gootieno/sneak-flix#21]
Hi ,your repo is great. Please tell me ,how to install and use ?
I have error result : "Database connection success! Sequelize is ready to use...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5432 ".

**Comment by gootieno** [comment]
Hi! Thank you for checking out my site! It is still a work in progress and am currently working things out to make it better. 

What steps did you take after loading the repo on your local machine? If you are having an issue running node it may be that port is already in use and you may have to terminate. First, start by figuring out which port is in use with sudo lsof -i :<enter port here > then you want to try kill -9 {PID} as the first command should give you a list of PID listening on that port. 

I hope this helps! Let me know if you run into more issues :)
